import time
import os
import pyautogui
import webbrowser

class CountryCodeException(Exception):
    pass 

def sendmsg_with_photo(message , mobile , imgpath):
    pyautogui.FAILSAFE = True  #to stop program go to screen corner
    webbrowser.open('https://web.whatsapp.com') #broser opens whatsapp web
    time.sleep(10) #sleep for 10s to wait for whatsapp to load 
    for phone_no in mobile: #for loop on mobile list
        if "+" not in phone_no: 
            raise CountryCodeException("Country code missing from phone_no")
        url = 'https://web.whatsapp.com/send?phone='+phone_no+'&text='+message
        pyautogui.click(x=878,y=74) #click on search bar of chrome
        pyautogui.write(url) #write url in search
        time.sleep(1) 
        pyautogui.press(['enter']) #press delete and enter 
        time.sleep(5) 
        xy = None 
        while xy is None:
            xy = pyautogui.locateCenterOnScreen(os.path.join(os.getcwd(),'attach.png'),grayscale=True) 
        pyautogui.click(xy)
        xy1= None 
        while xy1 is None:
            xy1=pyautogui.locateCenterOnScreen(os.path.join(os.getcwd(),'photo.png'),grayscale=True)
        pyautogui.click(xy1)
        time.sleep(2)
        pyautogui.write(imgpath)
        time.sleep(2)
        pyautogui.press('enter')
        time.sleep(2)
        pyautogui.press('enter')
        time.sleep(5)

def sendmsg_with_doc(message , mobile , filepath ,post = 0):
    pyautogui.FAILSAFE =True
    webbrowser.open('https://web.whatsapp.com')
    time.sleep(10)
    for phone_no in mobile:
        if "+" not in phone_no:
            raise CountryCodeException("Country code missing from phone_no")
        url = 'https://web.whatsapp.com/send?phone='+phone_no+'&text='+message
        pyautogui.click(x=878,y=74)
        pyautogui.write(url)
        time.sleep(1)
        pyautogui.press(['delete','enter'])
        time.sleep(6)
        if post == 0:
            pyautogui.press('enter')
            time.sleep(1)
        xy = None 
        while xy is None:
            xy=pyautogui.locateCenterOnScreen(os.path.join(os.getcwd(),'attach.png'),grayscale=True)
        pyautogui.click(xy)
        xy1= None 
        while xy1 is None:
            xy1=pyautogui.locateCenterOnScreen(os.path.join(os.getcwd(),'doc.png'),grayscale=True)
        pyautogui.click(xy1)
        time.sleep(3)
        pyautogui.write(filepath)
        time.sleep(1)
        pyautogui.press('enter')
        time.sleep(1)
        pyautogui.press('enter')
        time.sleep(1)
        if post == 1:
            pyautogui.press('enter')
        time.sleep(5)

def sendmsg(message , mobile):
    pyautogui.FAILSAFE =True
    webbrowser.open('https://web.whatsapp.com')
    time.sleep(10)
    for phone_no in mobile:
        if "+" not in phone_no:
            raise CountryCodeException("Country code missing from phone_no")
        url = 'https://web.whatsapp.com/send?phone='+phone_no+'&text='+message
        pyautogui.click(x=878,y=74)
        pyautogui.write(url)
        time.sleep(10)
        pyautogui.press(['delete','enter'])
        time.sleep(5)
        width,height = pyautogui.size()
        pyautogui.click(width/2,height/2)
        time.sleep(5)
        pyautogui.press('enter')
        time.sleep(1)
        pyautogui.press('enter')
        time.sleep(5)


if __name__ == '__main__':
    mobile = ['+91 70773 09693','+91 6204 986 350' ,'+91 79051 78143', '+91 75639 76701'] #numbers of to texted
    message = 'Hi! This is an autogenerated message'
    filepath = os.path.join(os.getcwd(),'pythonislove.png')
    sendmsg_with_photo(message, mobile , filepath)


